"use client";

import React, { useState } from "react";
import Image from "next/image";
import { motion, AnimatePresence } from "framer-motion";
import { Code, Eye, ExternalLink, Cpu, Layout, X } from "lucide-react";
import GlassCard from "./ui/GlassCard";

interface Project {
  id: number;
  title: string;
  category: "Development" | "Graphic Design" | "Automation";
  description: string;
  image: string;
  techStack: string[];
  features: string[];
  client: string;
  year: string;
}

const PROJECTS: Project[] = [
  {
    id: 1,
    title: "International E-commerce Website",
    category: "Development",
    description: "Developed a modern, high-performance e-commerce platform for an international client. Focused on creating a smooth digital checkout experience, lightning-fast load times, and a completely responsive mobile layout.",
    image: "/project1.png",
    techStack: ["Next.js", "React", "TypeScript", "Tailwind CSS", "Stripe API", "Node.js"],
    features: [
      "Dynamic catalog search and custom filter system",
      "Stripe payment integration with multi-currency handling",
      "Full localization support for multiple languages",
      "Comprehensive admin panel for managing inventory and orders",
    ],
    client: "Global Retailers Ltd",
    year: "2025",
  },
  {
    id: 2,
    title: "Brand Marketing Campaign",
    category: "Graphic Design",
    description: "Created social media graphics, custom advertisement creatives, and comprehensive marketing collateral for multiple high-growth businesses. Solved branding inconsistencies to deliver clean visual assets.",
    image: "/project2.png",
    techStack: ["Adobe Photoshop", "Adobe Illustrator", "Canva", "Figma"],
    features: [
      "Cohesive social media feed style guides and presets",
      "High-conversion ad banner sets for Meta & Google Ads",
      "Print-ready promotional brochures and business flyers",
      "Logo and typography variations for digital brands",
    ],
    client: "Lyvera Partners",
    year: "2025",
  },
  {
    id: 3,
    title: "AI Business Automation",
    category: "Automation",
    description: "Built end-to-end automated workflows using n8n and advanced AI model integrations to optimize business processes, filter leads, and cut down manual data insertion by 80%.",
    image: "/project3.png",
    techStack: ["n8n.io", "OpenAI API", "Google Sheets API", "Slack Webhooks", "Make.com"],
    features: [
      "Automatic email inquiry sorting and sentiment analysis",
      "Instant Slack notifications for priority leads",
      "Autogenerated CRM logging and database synchronization",
      "AI-driven initial reply generation for customer service",
    ],
    client: "Shift101 Operations",
    year: "2025",
  },
  {
    id: 4,
    title: "Business Website Development",
    category: "Development",
    description: "Designed and developed custom marketing websites for growing businesses, utilizing high-end animations and responsive frameworks to boost visitor conversion rates and enhance SEO presence.",
    image: "/project4.png",
    techStack: ["Next.js 15", "Framer Motion", "Tailwind CSS", "Vercel", "Lucide Icons"],
    features: [
      "Fluid scroll-linked animations and page transitions",
      "SEO audit score of 100 with server-side generation",
      "Interactive multi-step contact and quoting tools",
      "Accessible markup (WCAG 2.1 AA compliant)",
    ],
    client: "Emerging Tech Corp",
    year: "2025",
  },
];

const FILTERS: ("All" | "Development" | "Graphic Design" | "Automation")[] = [
  "All",
  "Development",
  "Graphic Design",
  "Automation",
];

export default function Projects() {
  const [filter, setFilter] = useState<"All" | "Development" | "Graphic Design" | "Automation">("All");
  const [selectedProject, setSelectedProject] = useState<Project | null>(null);

  const filteredProjects = PROJECTS.filter((p) => {
    if (filter === "All") return true;
    return p.category === filter;
  });

  return (
    <section
      id="projects"
      className="relative py-24 px-4 md:px-8 border-t dark:border-white/5 border-zinc-200 transition-colors duration-400"
      style={{ background: "var(--background)" }}
    >
      <div className="w-full max-w-5xl mx-auto space-y-16">
        
        {/* Section Title */}
        <div className="flex flex-col md:flex-row md:items-end justify-between gap-6">
          <div className="space-y-4 text-center md:text-left">
            <motion.h2
              initial={{ opacity: 0, y: 15 }}
              whileInView={{ opacity: 1, y: 0 }}
              viewport={{ once: true }}
              transition={{ duration: 0.6 }}
              className="text-xs font-bold tracking-widest text-blue-500 uppercase"
            >
              04 / Showcase
            </motion.h2>
            <motion.h3
              initial={{ opacity: 0, y: 20 }}
              whileInView={{ opacity: 1, y: 0 }}
              viewport={{ once: true }}
              transition={{ duration: 0.6, delay: 0.1 }}
              className="text-3xl sm:text-4xl font-extrabold dark:text-white text-zinc-900 tracking-tight uppercase"
            >
              Featured Projects
            </motion.h3>
          </div>

          {/* Filtering Tabs */}
          <div className="flex flex-wrap items-center justify-center gap-1 dark:bg-white/5 bg-zinc-100 p-1 rounded-full border dark:border-white/10 border-zinc-200 w-fit mx-auto md:mx-0">
            {FILTERS.map((cat) => (
              <button
                key={cat}
                onClick={() => setFilter(cat)}
                className={`px-4 py-1.5 rounded-full text-xs font-semibold uppercase tracking-wider transition-all duration-300 relative cursor-pointer ${
                  filter === cat ? "text-white" : "dark:text-zinc-400 text-zinc-500 dark:hover:text-zinc-200 hover:text-zinc-800"
                }`}
              >
                {filter === cat && (
                  <motion.span
                    layoutId="activeFilterBg"
                    className="absolute inset-0 bg-blue-500 rounded-full"
                    transition={{ type: "spring", stiffness: 380, damping: 30 }}
                  />
                )}
                <span className="relative z-10">{cat}</span>
              </button>
            ))}
          </div>
        </div>

        {/* Projects Grid */}
        <motion.div
          layout
          className="grid grid-cols-1 md:grid-cols-2 gap-6"
        >
          <AnimatePresence mode="popLayout">
            {filteredProjects.map((project) => (
              <motion.div
                key={project.id}
                layout
                initial={{ opacity: 0, scale: 0.95 }}
                animate={{ opacity: 1, scale: 1 }}
                exit={{ opacity: 0, scale: 0.95 }}
                transition={{ duration: 0.5, ease: [0.16, 1, 0.3, 1] }}
                className="group cursor-pointer"
                onClick={() => setSelectedProject(project)}
              >
                <GlassCard className="h-full border dark:border-white/5 border-zinc-200 p-0 overflow-hidden flex flex-col relative" hoverEffect={true}>
                  
                  {/* Thumbnail Image Container */}
                  <div className="relative aspect-video w-full overflow-hidden dark:bg-zinc-950 bg-zinc-100 border-b dark:border-white/5 border-zinc-200">
                    <Image
                      src={project.image}
                      alt={project.title}
                      fill
                      sizes="(max-w-768px) 100vw, 500px"
                      className="object-cover transition-transform duration-700 scale-100 group-hover:scale-105"
                    />
                    {/* Hover Overlay */}
                    <div className="absolute inset-0 dark:bg-[#08080a]/60 bg-white/60 opacity-0 group-hover:opacity-100 transition-opacity duration-300 flex items-center justify-center gap-3">
                      <div className="p-3 dark:bg-white/10 bg-black/10 rounded-full backdrop-blur-md border dark:border-white/20 border-zinc-300 dark:text-white text-zinc-800 transform translate-y-2 group-hover:translate-y-0 transition-transform duration-300">
                        <Eye size={20} />
                      </div>
                    </div>

                    {/* Category pill on image */}
                    <div className="absolute top-4 left-4 px-3 py-1 rounded-full dark:bg-black/60 bg-white/80 backdrop-blur-md border dark:border-white/10 border-zinc-200 text-[10px] font-bold dark:text-zinc-300 text-zinc-600 uppercase tracking-widest">
                      {project.category}
                    </div>
                  </div>

                  {/* Text Details */}
                  <div className="p-6 md:p-8 flex-1 flex flex-col justify-between gap-4">
                    <div className="space-y-2">
                      <h4 className="text-lg font-bold dark:text-white text-zinc-900 uppercase tracking-wider group-hover:text-blue-400 transition-colors">
                        {project.title}
                      </h4>
                      <p className="text-xs dark:text-zinc-400 text-zinc-500 leading-relaxed line-clamp-2">
                        {project.description}
                      </p>
                    </div>

                    {/* Tech tag list */}
                    <div className="flex flex-wrap items-center gap-1.5 pt-2">
                      {project.techStack.slice(0, 3).map((tech) => (
                        <span
                          key={tech}
                          className="px-2 py-0.5 rounded dark:bg-white/5 bg-zinc-100 border dark:border-white/5 border-zinc-200 text-[9px] font-bold dark:text-zinc-400 text-zinc-500 uppercase tracking-wider"
                        >
                          {tech}
                        </span>
                      ))}
                      {project.techStack.length > 3 && (
                        <span className="text-[9px] font-bold dark:text-zinc-500 text-zinc-400 tracking-wider">
                          +{project.techStack.length - 3} MORE
                        </span>
                      )}
                    </div>
                  </div>

                </GlassCard>
              </motion.div>
            ))}
          </AnimatePresence>
        </motion.div>

        {/* Project Modal Dialog */}
        <AnimatePresence>
          {selectedProject && (
            <div className="fixed inset-0 z-50 flex items-center justify-center p-4">
              {/* Backdrop */}
              <motion.div
                initial={{ opacity: 0 }}
                animate={{ opacity: 1 }}
                exit={{ opacity: 0 }}
                onClick={() => setSelectedProject(null)}
                className="absolute inset-0 dark:bg-[#08080a]/80 bg-black/40 backdrop-blur-sm"
              />

              {/* Modal Card */}
              <motion.div
                initial={{ opacity: 0, scale: 0.95, y: 20 }}
                animate={{ opacity: 1, scale: 1, y: 0 }}
                exit={{ opacity: 0, scale: 0.95, y: 20 }}
                transition={{ type: "spring", duration: 0.5 }}
                className="w-full max-w-2xl border rounded-3xl overflow-hidden shadow-[0_25px_60px_-15px_rgba(0,0,0,0.3)] dark:shadow-[0_25px_60px_-15px_rgba(0,0,0,0.9)] relative z-10 max-h-[90vh] flex flex-col"
                style={{ background: "var(--modal-bg)", borderColor: "var(--border-color)" }}
              >
                {/* Close Button */}
                <button
                  onClick={() => setSelectedProject(null)}
                  className="absolute top-4 right-4 z-20 p-2.5 rounded-full dark:bg-black/60 bg-zinc-100 border dark:border-white/10 border-zinc-200 dark:hover:bg-white/10 hover:bg-zinc-200 transition-colors dark:text-zinc-300 text-zinc-600 dark:hover:text-white hover:text-zinc-900 cursor-pointer"
                  aria-label="Close modal"
                >
                  <X size={16} />
                </button>

                {/* Modal Scrollable Container */}
                <div className="overflow-y-auto no-scrollbar flex-1">
                  
                  {/* Large Image Banner */}
                  <div className="relative aspect-video w-full dark:bg-zinc-950 bg-zinc-100 border-b dark:border-white/5 border-zinc-200">
                    <Image
                      src={selectedProject.image}
                      alt={selectedProject.title}
                      fill
                      sizes="600px"
                      className="object-cover"
                    />
                    <div className="absolute inset-0 bg-gradient-to-t dark:from-[#0b0b0e] from-white via-transparent to-transparent opacity-60" />
                  </div>

                  {/* Details */}
                  <div className="p-6 md:p-8 space-y-6">
                    
                    {/* Header info */}
                    <div className="space-y-2">
                      <div className="flex items-center gap-2">
                        <span className="px-2.5 py-0.5 rounded-full bg-blue-500/10 border border-blue-500/20 text-[10px] font-bold text-blue-400 uppercase tracking-widest">
                          {selectedProject.category}
                        </span>
                        <span className="text-[10px] font-bold dark:text-zinc-500 text-zinc-400 uppercase tracking-widest">
                          {selectedProject.year}
                        </span>
                      </div>
                      <h3 className="text-xl md:text-2xl font-extrabold dark:text-white text-zinc-900 uppercase tracking-wider">
                        {selectedProject.title}
                      </h3>
                      <p className="text-xs dark:text-zinc-500 text-zinc-400 font-bold uppercase tracking-wider">
                        Client: <span className="dark:text-zinc-300 text-zinc-600">{selectedProject.client}</span>
                      </p>
                    </div>

                    {/* Long Description */}
                    <div className="space-y-2">
                      <h5 className="text-xs font-bold dark:text-white text-zinc-900 uppercase tracking-widest">Overview</h5>
                      <p className="text-xs md:text-sm dark:text-zinc-400 text-zinc-500 leading-relaxed font-normal">
                        {selectedProject.description}
                      </p>
                    </div>

                    {/* Tech Stack List */}
                    <div className="space-y-3">
                      <h5 className="text-xs font-bold dark:text-white text-zinc-900 uppercase tracking-widest">Technologies Used</h5>
                      <div className="flex flex-wrap items-center gap-2">
                        {selectedProject.techStack.map((tech) => (
                          <span
                            key={tech}
                            className="px-3 py-1 rounded-md dark:bg-white/5 bg-zinc-100 border dark:border-white/5 border-zinc-200 text-[10px] font-bold dark:text-zinc-300 text-zinc-600 uppercase tracking-wider"
                          >
                            {tech}
                          </span>
                        ))}
                      </div>
                    </div>

                    {/* Key Accomplishments / Features */}
                    <div className="space-y-3">
                      <h5 className="text-xs font-bold dark:text-white text-zinc-900 uppercase tracking-widest">Key Accomplishments</h5>
                      <ul className="space-y-2">
                        {selectedProject.features.map((feat, idx) => (
                          <li key={idx} className="text-xs md:text-sm dark:text-zinc-400 text-zinc-500 leading-relaxed flex items-start gap-2">
                            <span className="text-blue-500 font-bold mt-1">•</span>
                            <span>{feat}</span>
                          </li>
                        ))}
                      </ul>
                    </div>

                  </div>

                </div>

              </motion.div>
            </div>
          )}
        </AnimatePresence>

      </div>
    </section>
  );
}
